### PR TITLE
Bump Go to 1.19

### PR DESCRIPTION
**Pull request by denyeart**
Bump Go to 1.19.

### CODE REVIEW

**Comment by denyeart** [comment]
@ale-linux @adecaro Not sure why license checks fails here. It passes on my local. My motivation here is to demonstrate that revocation_test.go failure as mentioned in https://github.com/hyperledger/fabric/pull/4164.

**Comment by ale-linux** [comment]
@denyeart I checked, this should fix the issue

```
diff --git a/Makefile b/Makefile
index 0c69793..f31860f 100644
--- a/Makefile
+++ b/Makefile
@@ -17,7 +17,7 @@ unit-tests-race:
 
 .PHONY: check-deps
 check-deps:
-       @go get -u github.com/google/addlicense
+       @go install github.com/google/addlicense@latest
 
 .PHONY: idemixgen
 idemixgen:
```

**Comment by ale-linux** [comment]
Ah, and you also need
```
diff --git a/bccsp/schemes/dlog/handlers/revocation_test.go b/bccsp/schemes/dlog/handlers/revocation_test.go
index 3e3dfa8..e17a503 100644
--- a/bccsp/schemes/dlog/handlers/revocation_test.go
+++ b/bccsp/schemes/dlog/handlers/revocation_test.go
@@ -50,7 +50,9 @@ var _ = Describe("Revocation", func() {
                                idemixRevocationKey = &ecdsa.PrivateKey{
                                        PublicKey: ecdsa.PublicKey{
                                                Curve: elliptic.P256(),
-                                               X:     big.NewInt(1), Y: big.NewInt(1)},
+                                               X:     elliptic.P256().Params().Gx,
+                                               Y:     elliptic.P256().Params().Gy,
+                                       },
                                        D: big.NewInt(1)}
 
                                raw := elliptic.Marshal(idemixRevocationKey.Curve, idemixRevocationKey.PublicKey.X, idemixRevocationKey.PublicKey.Y)
```
to get a unit test to run.

**Comment by denyeart** [comment]
@ale-linux Thanks, all done, I think this one is ready now.

**Review by ale-linux — APPROVED** [review]

**Pull request merged**
