### PR TITLE
add github.com/hyperledger/fabric-protos-go-apiv2

### PR DESCRIPTION
**Pull request by pfi79**
and downgrade gomega for fabric

it's an alternative to [pr](https://github.com/IBM/idemix/pull/48)
you can choose one of them or propose a 3rd alternative

https://github.com/hyperledger/fabric/issues/3650

### CODE REVIEW

**Comment by pfi79** [comment]
@ale-linux please allow the pipelines to run.

**Review by C0rWin — COMMENTED** [review]
the change is rather straight forward, and looks good, still I think the second opinion by @ale-linux or @yacovm would be great.

**Review by denyeart — APPROVED** [review]
LGTM, this PR follows the approach that we are using for the other fabric repositories.

**Review by denyeart — COMMENTED** [review]
@pfi79 In the other repositories, the direct dependency on github.com/golang/protobuf was changed to google.golang.org/protobuf. Is there a reason that is not done in this PR?

**Comment by ale-linux** [comment]
thanks for the patch. I see that we upgrade multiple packages in one single PR - let's split them for now and prioritise the protobuf upgrade. How about we just merge this

```
diff --git a/go.mod b/go.mod
index 9d025cc..8485ec3 100644
--- a/go.mod
+++ b/go.mod
@@ -10,7 +10,7 @@ require (
 	github.com/alecthomas/kingpin/v2 v2.4.0
 	github.com/golang/protobuf v1.5.4
 	github.com/hyperledger/aries-bbs-go v0.0.0-20240528084656-761671ea73bc
-	github.com/hyperledger/fabric-protos-go v0.3.3
+	github.com/hyperledger/fabric-protos-go-apiv2 v0.3.3
 	github.com/onsi/ginkgo v1.16.5
 	github.com/onsi/gomega v1.34.1
 	github.com/pkg/errors v0.9.1
@@ -26,20 +26,21 @@ require (
 	github.com/consensys/bavard v0.1.13 // indirect
 	github.com/consensys/gnark-crypto v0.13.0 // indirect
 	github.com/davecgh/go-spew v1.1.1 // indirect
-	github.com/fsnotify/fsnotify v1.7.0 // indirect
+	github.com/fsnotify/fsnotify v1.4.9 // indirect
 	github.com/google/go-cmp v0.6.0 // indirect
 	github.com/hyperledger/fabric-amcl v0.0.0-20230602173724-9e02669dceb2 // indirect
 	github.com/kilic/bls12-381 v0.1.0 // indirect
 	github.com/mmcloughlin/addchain v0.4.0 // indirect
-	github.com/nxadm/tail v1.4.11 // indirect
+	github.com/nxadm/tail v1.4.8 // indirect
 	github.com/pmezard/go-difflib v1.0.0 // indirect
 	github.com/xhit/go-str2duration/v2 v2.1.0 // indirect
 	go.uber.org/multierr v1.11.0 // indirect
 	golang.org/x/crypto v0.26.0 // indirect
-	golang.org/x/exp v0.0.0-20240808152545-0cdaa3abc0fa // indirect
+	golang.org/x/exp v0.0.0-20240719175910-8a7402abbf56 // indirect
 	golang.org/x/net v0.28.0 // indirect
 	golang.org/x/sys v0.24.0 // indirect
 	golang.org/x/text v0.17.0 // indirect
+	golang.org/x/tools v0.24.0 // indirect
 	google.golang.org/protobuf v1.34.2 // indirect
 	gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7 // indirect
 	gopkg.in/yaml.v3 v3.0.1 // indirect
diff --git a/go.sum b/go.sum
index 98e787b..a591c3d 100644
--- a/go.sum
+++ b/go.sum
@@ -19,10 +19,8 @@ github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSs
 github.com/davecgh/go-spew v1.1.1 h1:vj9j/u1bqnvCEfJOwUhtlOARqs3+rkHYY13jYWTU97c=
 github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
 github.com/fsnotify/fsnotify v1.4.7/go.mod h1:jwhsz4b93w/PPRr/qN1Yymfu8t87LnFCMoQvtojpjFo=
+github.com/fsnotify/fsnotify v1.4.9 h1:hsms1Qyu0jgnwNXIxa+/V/PDsU6CfLf6CNO8H7IWoS4=
 github.com/fsnotify/fsnotify v1.4.9/go.mod h1:znqG4EE+3YCdAaPaxE2ZRY/06pZUdp0tY4IgpuI1SZQ=
-github.com/fsnotify/fsnotify v1.6.0/go.mod h1:sl3t1tCWJFWoRz9R8WJCbQihKKwmorjAbSClcnxKAGw=
-github.com/fsnotify/fsnotify v1.7.0 h1:8JEhPFa5W2WU7YfeZzPNqzMP6Lwt7L2715Ggo0nosvA=
-github.com/fsnotify/fsnotify v1.7.0/go.mod h1:40Bi/Hjc2AVfZrqy+aj+yEI+/bRxZnMJyTJwOpGvigM=
 github.com/go-logr/logr v1.4.1 h1:pKouT5E8xu9zeFC39JXRDukb6JFQPXM5p5I91188VAQ=
 github.com/go-logr/logr v1.4.1/go.mod h1:9T104GzyrTigFIr8wt5mBrctHMim0Nb2HLGrmQ40KvY=
 github.com/go-task/slim-sprig v0.0.0-20210107165309-348f09dbbbc0 h1:p104kn46Q8WdvHunIJ9dAyjPVtrBPhSr3KT2yUst43I=
@@ -52,8 +50,8 @@ github.com/hyperledger/aries-bbs-go v0.0.0-20240528084656-761671ea73bc h1:3Ykk6M
 github.com/hyperledger/aries-bbs-go v0.0.0-20240528084656-761671ea73bc/go.mod h1:Kofn6A6WWea1ZM8Rys5aBW9dszwJ7Ywa0kyyYL0TPYw=
 github.com/hyperledger/fabric-amcl v0.0.0-20230602173724-9e02669dceb2 h1:B1Nt8hKb//KvgGRprk0h1t4lCnwhE9/ryb1WqfZbV+M=
 github.com/hyperledger/fabric-amcl v0.0.0-20230602173724-9e02669dceb2/go.mod h1:X+DIyUsaTmalOpmpQfIvFZjKHQedrURQ5t4YqquX7lE=
-github.com/hyperledger/fabric-protos-go v0.3.3 h1:0nssqz8QWJNVNBVQz+IIfAd2j1ku7QPKFSM/1anKizI=
-github.com/hyperledger/fabric-protos-go v0.3.3/go.mod h1:BPXse9gIOQwyAePQrwQVUcc44bTW4bB5V3tujuvyArk=
+github.com/hyperledger/fabric-protos-go-apiv2 v0.3.3 h1:Xpd6fzG/KjAOHJsq7EQXY2l+qi/y8muxBaY7R6QWABk=
+github.com/hyperledger/fabric-protos-go-apiv2 v0.3.3/go.mod h1:2pq0ui6ZWA0cC8J+eCErgnMDCS1kPOEYVY+06ZAK0qE=
 github.com/kilic/bls12-381 v0.1.0 h1:encrdjqKMEvabVQ7qYOKu1OvhqpK4s47wDYtNiPtlp4=
 github.com/kilic/bls12-381 v0.1.0/go.mod h1:vDTTHJONJ6G+P2R74EhnyotQDTliQDnFEwhdmfzw1ig=
 github.com/kisielk/gotool v1.0.0/go.mod h1:XhKaO+MFFWcvkIS/tQcRk01m1F5IRFswLeQ+oQHNcck=
@@ -70,9 +68,8 @@ github.com/mmcloughlin/addchain v0.4.0 h1:SobOdjm2xLj1KkXN5/n0xTIWyZA2+s99UCY1iP
 github.com/mmcloughlin/addchain v0.4.0/go.mod h1:A86O+tHqZLMNO4w6ZZ4FlVQEadcoqkyU72HC5wJ4RlU=
 github.com/mmcloughlin/profile v0.1.1/go.mod h1:IhHD7q1ooxgwTgjxQYkACGA77oFTDdFVejUS1/tS/qU=
 github.com/nxadm/tail v1.4.4/go.mod h1:kenIhsEOeOJmVchQTgglprH7qJGnHDVpk1VPCcaMI8A=
+github.com/nxadm/tail v1.4.8 h1:nPr65rt6Y5JFSKQO7qToXr7pePgD6Gwiw05lkbyAQTE=
 github.com/nxadm/tail v1.4.8/go.mod h1:+ncqLTQzXmGhMZNUePPaPqPvBxHAIsmXswZKocGu+AU=
-github.com/nxadm/tail v1.4.11 h1:8feyoE3OzPrcshW5/MJ4sGESc5cqmGkGCWlco4l0bqY=
-github.com/nxadm/tail v1.4.11/go.mod h1:OTaG3NK980DZzxbRq6lEuzgU+mug70nY11sMd4JXXHc=
 github.com/onsi/ginkgo v1.6.0/go.mod h1:lLunBs/Ym6LB5Z9jYTR76FiuTmxDTDusOGeTQH+WWjE=
 github.com/onsi/ginkgo v1.12.1/go.mod h1:zj2OWP4+oCPe1qIXoGWkgMRwljMUYCdkwsT2108oapk=
 github.com/onsi/ginkgo v1.16.5 h1:8xi0RTUf59SOSfEtZMvwTvXYMzG4gV23XVHOZiXNtnE=
@@ -124,8 +121,8 @@ golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550/go.mod h1:yigFU9vqHzYiE8U
 golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9/go.mod h1:LzIPMQfyMNhhGPhUkYOs5KpL4U8rLKemX1yGLhDgUto=
 golang.org/x/crypto v0.26.0 h1:RrRspgV4mU+YwB4FYnuBoKsUapNIL5cohGAmSH3azsw=
 golang.org/x/crypto v0.26.0/go.mod h1:GY7jblb9wI+FOo5y8/S2oY4zWP07AkOJ4+jxCqdqn54=
-golang.org/x/exp v0.0.0-20240808152545-0cdaa3abc0fa h1:ELnwvuAXPNtPk1TJRuGkI9fDTwym6AYBu0qzT8AcHdI=
-golang.org/x/exp v0.0.0-20240808152545-0cdaa3abc0fa/go.mod h1:akd2r19cwCdwSwWeIdzYQGa/EZZyqcOdwWiwj5L5eKQ=
+golang.org/x/exp v0.0.0-20240719175910-8a7402abbf56 h1:2dVuKD2vS7b0QIHQbpyTISPd0LeHDbnYEryqj5Q1ug8=
+golang.org/x/exp v0.0.0-20240719175910-8a7402abbf56/go.mod h1:M4RDyNAINzryxdtnbRXRL/OHtkFuWGRjvuhBJpk2IlY=
 golang.org/x/lint v0.0.0-20190930215403-16217165b5de/go.mod h1:6SW0HCj/g11FgYtHlgUYUwCkIfeOF89ocIRzGO/8vkc=
 golang.org/x/mod v0.0.0-20190513183733-4bf6d317e70e/go.mod h1:mXi4GBBbnImb6dmsKGUJ2LatrhH/nqhxcFungHvyanc=
 golang.org/x/mod v0.3.0/go.mod h1:s0Qsj1ACt9ePp/hMypM3fl4fZqREWJwdYDEqhRiZZUA=
@@ -150,7 +147,6 @@ golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd/go.mod h1:h1NjWce9XRLGQEsW7w
 golang.org/x/sys v0.0.0-20200930185726-fdedc70b468f/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
 golang.org/x/sys v0.0.0-20201101102859-da207088b7d1/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
 golang.org/x/sys v0.0.0-20210112080510-489259a85091/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
-golang.org/x/sys v0.0.0-20220908164124-27713097b956/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
 golang.org/x/sys v0.24.0 h1:Twjiwq9dn6R1fQcyiK+wQyHWfaz/BJB+YIpzU/Cv3Xg=
 golang.org/x/sys v0.24.0/go.mod h1:/VUhepiaJMQUp4+oa/7Zr1D23ma6VTLIYjOOTFZPUcA=
 golang.org/x/text v0.3.0/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
diff --git a/idemix_roles.go b/idemix_roles.go
index 53e823b..aa3a7a0 100644
--- a/idemix_roles.go
+++ b/idemix_roles.go
@@ -6,7 +6,7 @@ SPDX-License-Identifier: Apache-2.0
 package idemix
 
 import (
-	m "github.com/hyperledger/fabric-protos-go/msp"
+	m "github.com/hyperledger/fabric-protos-go-apiv2/msp"
 )
 
 // Role : Represents a IdemixRole
diff --git a/idemixmsp.go b/idemixmsp.go
index 3454245..37ea48e 100644
--- a/idemixmsp.go
+++ b/idemixmsp.go
@@ -22,7 +22,7 @@ import (
 	im "github.com/IBM/idemix/idemixmsp"
 	math "github.com/IBM/mathlib"
 	"github.com/golang/protobuf/proto"
-	m "github.com/hyperledger/fabric-protos-go/msp"
+	m "github.com/hyperledger/fabric-protos-go-apiv2/msp"
 	"github.com/pkg/errors"
 	"go.uber.org/zap/zapcore"
 )
diff --git a/idemixmsp_aries_test.go b/idemixmsp_aries_test.go
index f2a95fc..4f1e148 100644
--- a/idemixmsp_aries_test.go
+++ b/idemixmsp_aries_test.go
@@ -10,7 +10,7 @@ import (
 	"testing"
 
 	"github.com/golang/protobuf/proto"
-	"github.com/hyperledger/fabric-protos-go/msp"
+	"github.com/hyperledger/fabric-protos-go-apiv2/msp"
 	"github.com/stretchr/testify/require"
 )
 
diff --git a/idemixmsp_test.go b/idemixmsp_test.go
index 85f4a65..f51315c 100644
--- a/idemixmsp_test.go
+++ b/idemixmsp_test.go
@@ -14,7 +14,7 @@ import (
 	im "github.com/IBM/idemix/idemixmsp"
 	math "github.com/IBM/mathlib"
 	"github.com/golang/protobuf/proto"
-	"github.com/hyperledger/fabric-protos-go/msp"
+	"github.com/hyperledger/fabric-protos-go-apiv2/msp"
 	"github.com/pkg/errors"
 	"github.com/stretchr/testify/require"
 )
diff --git a/msp.go b/msp.go
index cc07a74..daad00c 100644
--- a/msp.go
+++ b/msp.go
@@ -9,7 +9,7 @@ package idemix
 import (
 	"time"
 
-	"github.com/hyperledger/fabric-protos-go/msp"
+	"github.com/hyperledger/fabric-protos-go-apiv2/msp"
 )
 
 // IdentityDeserializer is implemented by both MSPManger and MSP
```

for now? @pfi79

**Comment by denyeart** [comment]
@pfi79 Additionally, instead of a gomega downgrade here, can we upgrade gomega in fabric?

**Comment by ale-linux** [comment]
@pfi79 if you are okay with merging just that for now - pls go ahead and force-push. I'll re-run the CI and merge

**Comment by pfi79** [comment]
> @pfi79 Additionally, instead of a gomega downgrade here, can we upgrade gomega in fabric?

For some reason, I don't know yet why. upgrading gomega version causes raft integration tests to fail. This requires separate investigation.

**Comment by pfi79** [comment]
> thanks for the patch. I see that we upgrade multiple packages in one single PR - let's split them for now and prioritise the protobuf upgrade. How about we just merge this
> 
> ```
> diff --git a/go.mod b/go.mod
> index 9d025cc..8485ec3 100644
> --- a/go.mod
> +++ b/go.mod
> @@ -10,7 +10,7 @@ require (
>  	github.com/alecthomas/kingpin/v2 v2.4.0
>  	github.com/golang/protobuf v1.5.4
>  	github.com/hyperledger/aries-bbs-go v0.0.0-20240528084656-761671ea73bc
> -	github.com/hyperledger/fabric-protos-go v0.3.3
> +	github.com/hyperledger/fabric-protos-go-apiv2 v0.3.3
>  	github.com/onsi/ginkgo v1.16.5
>  	github.com/onsi/gomega v1.34.1
>  	github.com/pkg/errors v0.9.1
> @@ -26,20 +26,21 @@ require (
>  	github.com/consensys/bavard v0.1.13 // indirect
>  	github.com/consensys/gnark-crypto v0.13.0 // indirect
>  	github.com/davecgh/go-spew v1.1.1 // indirect
> -	github.com/fsnotify/fsnotify v1.7.0 // indirect
> +	github.com/fsnotify/fsnotify v1.4.9 // indirect
>  	github.com/google/go-cmp v0.6.0 // indirect
>  	github.com/hyperledger/fabric-amcl v0.0.0-20230602173724-9e02669dceb2 // indirect
>  	github.com/kilic/bls12-381 v0.1.0 // indirect
>  	github.com/mmcloughlin/addchain v0.4.0 // indirect
> -	github.com/nxadm/tail v1.4.11 // indirect
> +	github.com/nxadm/tail v1.4.8 // indirect
>  	github.com/pmezard/go-difflib v1.0.0 // indirect
>  	github.com/xhit/go-str2duration/v2 v2.1.0 // indirect
>  	go.uber.org/multierr v1.11.0 // indirect
>  	golang.org/x/crypto v0.26.0 // indirect
> -	golang.org/x/exp v0.0.0-20240808152545-0cdaa3abc0fa // indirect
> +	golang.org/x/exp v0.0.0-20240719175910-8a7402abbf56 // indirect
>  	golang.org/x/net v0.28.0 // indirect
>  	golang.org/x/sys v0.24.0 // indirect
>  	golang.org/x/text v0.17.0 // indirect
> +	golang.org/x/tools v0.24.0 // indirect
>  	google.golang.org/protobuf v1.34.2 // indirect
>  	gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7 // indirect
>  	gopkg.in/yaml.v3 v3.0.1 // indirect
> diff --git a/go.sum b/go.sum
> index 98e787b..a591c3d 100644
> --- a/go.sum
> +++ b/go.sum
> @@ -19,10 +19,8 @@ github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSs
>  github.com/davecgh/go-spew v1.1.1 h1:vj9j/u1bqnvCEfJOwUhtlOARqs3+rkHYY13jYWTU97c=
>  github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
>  github.com/fsnotify/fsnotify v1.4.7/go.mod h1:jwhsz4b93w/PPRr/qN1Yymfu8t87LnFCMoQvtojpjFo=
> +github.com/fsnotify/fsnotify v1.4.9 h1:hsms1Qyu0jgnwNXIxa+/V/PDsU6CfLf6CNO8H7IWoS4=
>  github.com/fsnotify/fsnotify v1.4.9/go.mod h1:znqG4EE+3YCdAaPaxE2ZRY/06pZUdp0tY4IgpuI1SZQ=
> -github.com/fsnotify/fsnotify v1.6.0/go.mod h1:sl3t1tCWJFWoRz9R8WJCbQihKKwmorjAbSClcnxKAGw=
> -github.com/fsnotify/fsnotify v1.7.0 h1:8JEhPFa5W2WU7YfeZzPNqzMP6Lwt7L2715Ggo0nosvA=
> -github.com/fsnotify/fsnotify v1.7.0/go.mod h1:40Bi/Hjc2AVfZrqy+aj+yEI+/bRxZnMJyTJwOpGvigM=
>  github.com/go-logr/logr v1.4.1 h1:pKouT5E8xu9zeFC39JXRDukb6JFQPXM5p5I91188VAQ=
>  github.com/go-logr/logr v1.4.1/go.mod h1:9T104GzyrTigFIr8wt5mBrctHMim0Nb2HLGrmQ40KvY=
>  github.com/go-task/slim-sprig v0.0.0-20210107165309-348f09dbbbc0 h1:p104kn46Q8WdvHunIJ9dAyjPVtrBPhSr3KT2yUst43I=
> @@ -52,8 +50,8 @@ github.com/hyperledger/aries-bbs-go v0.0.0-20240528084656-761671ea73bc h1:3Ykk6M
>  github.com/hyperledger/aries-bbs-go v0.0.0-20240528084656-761671ea73bc/go.mod h1:Kofn6A6WWea1ZM8Rys5aBW9dszwJ7Ywa0kyyYL0TPYw=
>  github.com/hyperledger/fabric-amcl v0.0.0-20230602173724-9e02669dceb2 h1:B1Nt8hKb//KvgGRprk0h1t4lCnwhE9/ryb1WqfZbV+M=
>  github.com/hyperledger/fabric-amcl v0.0.0-20230602173724-9e02669dceb2/go.mod h1:X+DIyUsaTmalOpmpQfIvFZjKHQedrURQ5t4YqquX7lE=
> -github.com/hyperledger/fabric-protos-go v0.3.3 h1:0nssqz8QWJNVNBVQz+IIfAd2j1ku7QPKFSM/1anKizI=
> -github.com/hyperledger/fabric-protos-go v0.3.3/go.mod h1:BPXse9gIOQwyAePQrwQVUcc44bTW4bB5V3tujuvyArk=
> +github.com/hyperledger/fabric-protos-go-apiv2 v0.3.3 h1:Xpd6fzG/KjAOHJsq7EQXY2l+qi/y8muxBaY7R6QWABk=
> +github.com/hyperledger/fabric-protos-go-apiv2 v0.3.3/go.mod h1:2pq0ui6ZWA0cC8J+eCErgnMDCS1kPOEYVY+06ZAK0qE=
>  github.com/kilic/bls12-381 v0.1.0 h1:encrdjqKMEvabVQ7qYOKu1OvhqpK4s47wDYtNiPtlp4=
>  github.com/kilic/bls12-381 v0.1.0/go.mod h1:vDTTHJONJ6G+P2R74EhnyotQDTliQDnFEwhdmfzw1ig=
>  github.com/kisielk/gotool v1.0.0/go.mod h1:XhKaO+MFFWcvkIS/tQcRk01m1F5IRFswLeQ+oQHNcck=
> @@ -70,9 +68,8 @@ github.com/mmcloughlin/addchain v0.4.0 h1:SobOdjm2xLj1KkXN5/n0xTIWyZA2+s99UCY1iP
>  github.com/mmcloughlin/addchain v0.4.0/go.mod h1:A86O+tHqZLMNO4w6ZZ4FlVQEadcoqkyU72HC5wJ4RlU=
>  github.com/mmcloughlin/profile v0.1.1/go.mod h1:IhHD7q1ooxgwTgjxQYkACGA77oFTDdFVejUS1/tS/qU=
>  github.com/nxadm/tail v1.4.4/go.mod h1:kenIhsEOeOJmVchQTgglprH7qJGnHDVpk1VPCcaMI8A=
> +github.com/nxadm/tail v1.4.8 h1:nPr65rt6Y5JFSKQO7qToXr7pePgD6Gwiw05lkbyAQTE=
>  github.com/nxadm/tail v1.4.8/go.mod h1:+ncqLTQzXmGhMZNUePPaPqPvBxHAIsmXswZKocGu+AU=
> -github.com/nxadm/tail v1.4.11 h1:8feyoE3OzPrcshW5/MJ4sGESc5cqmGkGCWlco4l0bqY=
> -github.com/nxadm/tail v1.4.11/go.mod h1:OTaG3NK980DZzxbRq6lEuzgU+mug70nY11sMd4JXXHc=
>  github.com/onsi/ginkgo v1.6.0/go.mod h1:lLunBs/Ym6LB5Z9jYTR76FiuTmxDTDusOGeTQH+WWjE=
>  github.com/onsi/ginkgo v1.12.1/go.mod h1:zj2OWP4+oCPe1qIXoGWkgMRwljMUYCdkwsT2108oapk=
>  github.com/onsi/ginkgo v1.16.5 h1:8xi0RTUf59SOSfEtZMvwTvXYMzG4gV23XVHOZiXNtnE=
> @@ -124,8 +121,8 @@ golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550/go.mod h1:yigFU9vqHzYiE8U
>  golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9/go.mod h1:LzIPMQfyMNhhGPhUkYOs5KpL4U8rLKemX1yGLhDgUto=
>  golang.org/x/crypto v0.26.0 h1:RrRspgV4mU+YwB4FYnuBoKsUapNIL5cohGAmSH3azsw=
>  golang.org/x/crypto v0.26.0/go.mod h1:GY7jblb9wI+FOo5y8/S2oY4zWP07AkOJ4+jxCqdqn54=
> -golang.org/x/exp v0.0.0-20240808152545-0cdaa3abc0fa h1:ELnwvuAXPNtPk1TJRuGkI9fDTwym6AYBu0qzT8AcHdI=
> -golang.org/x/exp v0.0.0-20240808152545-0cdaa3abc0fa/go.mod h1:akd2r19cwCdwSwWeIdzYQGa/EZZyqcOdwWiwj5L5eKQ=
> +golang.org/x/exp v0.0.0-20240719175910-8a7402abbf56 h1:2dVuKD2vS7b0QIHQbpyTISPd0LeHDbnYEryqj5Q1ug8=
> +golang.org/x/exp v0.0.0-20240719175910-8a7402abbf56/go.mod h1:M4RDyNAINzryxdtnbRXRL/OHtkFuWGRjvuhBJpk2IlY=
>  golang.org/x/lint v0.0.0-20190930215403-16217165b5de/go.mod h1:6SW0HCj/g11FgYtHlgUYUwCkIfeOF89ocIRzGO/8vkc=
>  golang.org/x/mod v0.0.0-20190513183733-4bf6d317e70e/go.mod h1:mXi4GBBbnImb6dmsKGUJ2LatrhH/nqhxcFungHvyanc=
>  golang.org/x/mod v0.3.0/go.mod h1:s0Qsj1ACt9ePp/hMypM3fl4fZqREWJwdYDEqhRiZZUA=
> @@ -150,7 +147,6 @@ golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd/go.mod h1:h1NjWce9XRLGQEsW7w
>  golang.org/x/sys v0.0.0-20200930185726-fdedc70b468f/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
>  golang.org/x/sys v0.0.0-20201101102859-da207088b7d1/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
>  golang.org/x/sys v0.0.0-20210112080510-489259a85091/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
> -golang.org/x/sys v0.0.0-20220908164124-27713097b956/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
>  golang.org/x/sys v0.24.0 h1:Twjiwq9dn6R1fQcyiK+wQyHWfaz/BJB+YIpzU/Cv3Xg=
>  golang.org/x/sys v0.24.0/go.mod h1:/VUhepiaJMQUp4+oa/7Zr1D23ma6VTLIYjOOTFZPUcA=
>  golang.org/x/text v0.3.0/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
> diff --git a/idemix_roles.go b/idemix_roles.go
> index 53e823b..aa3a7a0 100644
> --- a/idemix_roles.go
> +++ b/idemix_roles.go
> @@ -6,7 +6,7 @@ SPDX-License-Identifier: Apache-2.0
>  package idemix
>  
>  import (
> -	m "github.com/hyperledger/fabric-protos-go/msp"
> +	m "github.com/hyperledger/fabric-protos-go-apiv2/msp"
>  )
>  
>  // Role : Represents a IdemixRole
> diff --git a/idemixmsp.go b/idemixmsp.go
> index 3454245..37ea48e 100644
> --- a/idemixmsp.go
> +++ b/idemixmsp.go
> @@ -22,7 +22,7 @@ import (
>  	im "github.com/IBM/idemix/idemixmsp"
>  	math "github.com/IBM/mathlib"
>  	"github.com/golang/protobuf/proto"
> -	m "github.com/hyperledger/fabric-protos-go/msp"
> +	m "github.com/hyperledger/fabric-protos-go-apiv2/msp"
>  	"github.com/pkg/errors"
>  	"go.uber.org/zap/zapcore"
>  )
> diff --git a/idemixmsp_aries_test.go b/idemixmsp_aries_test.go
> index f2a95fc..4f1e148 100644
> --- a/idemixmsp_aries_test.go
> +++ b/idemixmsp_aries_test.go
> @@ -10,7 +10,7 @@ import (
>  	"testing"
>  
>  	"github.com/golang/protobuf/proto"
> -	"github.com/hyperledger/fabric-protos-go/msp"
> +	"github.com/hyperledger/fabric-protos-go-apiv2/msp"
>  	"github.com/stretchr/testify/require"
>  )
>  
> diff --git a/idemixmsp_test.go b/idemixmsp_test.go
> index 85f4a65..f51315c 100644
> --- a/idemixmsp_test.go
> +++ b/idemixmsp_test.go
> @@ -14,7 +14,7 @@ import (
>  	im "github.com/IBM/idemix/idemixmsp"
>  	math "github.com/IBM/mathlib"
>  	"github.com/golang/protobuf/proto"
> -	"github.com/hyperledger/fabric-protos-go/msp"
> +	"github.com/hyperledger/fabric-protos-go-apiv2/msp"
>  	"github.com/pkg/errors"
>  	"github.com/stretchr/testify/require"
>  )
> diff --git a/msp.go b/msp.go
> index cc07a74..daad00c 100644
> --- a/msp.go
> +++ b/msp.go
> @@ -9,7 +9,7 @@ package idemix
>  import (
>  	"time"
>  
> -	"github.com/hyperledger/fabric-protos-go/msp"
> +	"github.com/hyperledger/fabric-protos-go-apiv2/msp"
>  )
>  
>  // IdentityDeserializer is implemented by both MSPManger and MSP
> ```
> 
> for now? @pfi79 
> 
> 

The thing is that I wanted to change fabric-protos-go-apiv2 first. But then fabric will pull in the new version of gomega from idemix. But for some reason, with the new version of gomega, raft integration tests in fabric fail. I can make 2 pr: first gomega, then fabric-protos-go-apiv2

**Review by ale-linux — APPROVED** [review]

**Comment by ale-linux** [comment]
sounds good - let's go with this then

**Pull request merged**
